### ISSUE TITLE
BME280 | bme280 stops after the first reading

### ISSUE THREAD

**Issue by floriandusch** [kmetz/coro2sens#3]
Hi @kmetz,
thanks a lot for the great instructions. Everything works beautifully over here.
The only small issue i have is, that `bme280isConnected` changes to false after the first reading of the BME280 sensor.
I can't seem to solve it... any pointers?

Thanks much in advance!

**Comment by kmetz** [comment]
Thanks! I will look into this ASAP.

**Comment by kmetz** [comment]
Ok, with the much appreciated help and feedback of @htor-j I was able to fix this, BME280 has to run in `MODE_NORMAL` instead of `MODE_FORCED`, the latter requires to re-set forced mode before each reading (it goes into sleep mode afterwards). Normal mode will update readings internally periodically and is also recommended when using filters (see datasheet).

**Comment by kmetz** [comment]
Please use 71cc1216 / v1.2.2 +.

**Comment by floriandusch** [comment]
It's working now. Thanks for the fix, @kmetz!
